### ISSUE TITLE
result_lap_data errors out if the driver did not complete any laps

### ISSUE THREAD

**Issue by mrzepka** [jasondilworth56/iracingdataapi#11]
`TypeError: 'NoneType' object is not subscriptable`

This error shows up because if a person registers, but does not complete a lap, the result from /data/results/lap_data is None for that cust_id and subsession_id. 

We could either return "None" or an empty array I believe.

**Comment by jasondilworth56** [comment]
Thanks for the heads up – do you have a `subsession_id` and `cust_id` or `team_id` that I can test with?

**Comment by mrzepka** [comment]
I found it with my own. I registered, my internet cut out, and I could never actually join the session.:

subsession_id=58568757
cust_id=573444

**Comment by jasondilworth56** [comment]
This is now fixed in 1.0.6 which you can upgrade to with `pip install --upgrade iracingdataapi`. Thanks again for the heads up!
