### ISSUE TITLE
Rate-limiting errors out

### ISSUE THREAD

**Issue by mrzepka** [jasondilworth56/iracingdataapi#12]
https://github.com/jasondilworth56/iracingdataapi/blob/df3a52923be508db1f0684bd4f6aaa0f0d632017/src/iracingdataapi/client.py#L75

In my repeated rapid abuse of the api, I came upon this:

File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\iracingdataapi\client.py", line 90, in _get_resource
    resource_obj, is_link = self._get_resource_or_link(request_url, payload=payload)
  File "C:\Users\matth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\iracingdataapi\client.py", line 75, in _get_resource_or_link
    reset_datetime = datetime.fromtimestamp(r.header["x-ratelimit-reset"])
AttributeError: 'Response' object has no attribute 'header'. Did you mean: 'headers'?

Looks like we just need to update r.header -> r.headers?

**Comment by jasondilworth56** [comment]
Oh dear, that's a bit of an oversight, sorry!

Do you fancy sorting out and testing the fix and I'll get it into the next update?

**Comment by mrzepka** [comment]
I made the change and am working to test it. I'm struggling to actually reproduce the issue ever since I opened this issue.

**Comment by mrzepka** [comment]
I managed to get my code to run fast enough to rate limit again. I ran into some strange edgecase here where the x-ratelimit-reset header managed to be before datetime.now, which throws an error when trying to sleep:

Rate limited, waiting
reset_datetime: 2023-01-23 17:46:33
datetime now  : 2023-01-23 17:46:33.029397
delta         : -1 day, 23:59:59.970603


and 

Rate limited, waiting
reset_datetime: 2023-01-23 17:49:33
datetime now  : 2023-01-23 17:49:15.869170
delta         : 17.13083
Rate limited, waiting
reset_datetime: 2023-01-23 17:49:33
datetime now  : 2023-01-23 17:49:33.070389
delta         : -0.070389


I propose adding 1 (or more) to the delta.

**Comment by mrzepka** [comment]
Here is my excellent debugging with 1 second added to the delta:

Rate limited, waiting
reset_datetime: 2023-01-23 17:52:21
datetime now  : 2023-01-23 17:52:15.348002
delta         : 5.651998
delta + 1     : 6.651998
Rate limited, waiting
reset_datetime: 2023-01-23 17:52:21
datetime now  : 2023-01-23 17:52:21.026266
delta         : -0.026266
delta + 1     : 0.973734

**Comment by mrzepka** [comment]
I think it may be broken due to the retry, but I can't work out exactly why. It's the same scenario where it gets ratelimited 2x but the second time breaks it.

reset_datetime: 2023-01-23 17:54:09
datetime now  : 2023-01-23 17:53:47.773792
delta         : 21.226208
delta + 1     : 22.226208
Rate limited, waiting
reset_datetime: 2023-01-23 17:54:09
datetime now  : 2023-01-23 17:54:10.022771
delta         : -1.022771
delta + 1     : -0.022771000000000097


This was after I added 1 to the sleep function thinking sleeping later would save it.

**Comment by jasondilworth56** [comment]
Fixed by #13
