### ISSUE TITLE
Are cookies really working?

### ISSUE THREAD

**Issue by musantro** [jasondilworth56/iracingdataapi#14]
Hi, 

I've tried to create an `irDataClient` like this:

```python
idc = irDataClient(username, password, cookie_file='cookie-jar.txt')
```

But I don't see any `cookie-jar.txt` created in the working directory where the script is initiated.

I took a look to the source code:

https://github.com/jasondilworth56/iracingdataapi/blob/df3a52923be508db1f0684bd4f6aaa0f0d632017/src/iracingdataapi/client.py#L27-L35

method `self._login()` is only called here:
https://github.com/jasondilworth56/iracingdataapi/blob/df3a52923be508db1f0684bd4f6aaa0f0d632017/src/iracingdataapi/client.py#L63

I would expect to pass `self.cookies_file` to the method, or directly use `self.cookies_file` (which is accepted in the `__init__` method but it's not stored in `self`?) inside the `_login(...)` method.

I could send a PR fixing this but I wanted first to discuss here just to be sure.

Thank you in advance!

**Comment by jasondilworth56** [comment]
That looks like an oversight. Quickest way to check you get what you expect it to call `_login()` manually with `cookie_file`.

As you've mentioned, there'd then need to be work on the `__init__` method as well to make it work. This is clearly a bit of functionality I've meant to implement at some point and missed because I don't personally use it. Sorry it's not working as you like yet.

**Comment by musantro** [comment]
Thanks for the quick reply @jasondilworth56 ! I will definitely come up with a PR with a working solution, but first I would like to discuss some points.

First, As an API user, I would expect to use cookies as the default behaviour if no `cookie_file` is specified while instantiating a `irDataClient`, which I suspect it is not by looking at the code; iRacing really encourages people to use the API to use and reuse cookies, as mentioned in this PR #5.

Second, to be honest, even if we store into `irDataClient` object the `cookie_file` attribute,  I feel a bit confused about what would be the real purpose for it, rather than just giving a custom file name to the cookie file. If this is the unique purpose, then it's okay.

**Comment by jasondilworth56** [comment]
Well the reason it's all defunct is because of the use of `requests.Session` which handles the cookie side for us. I presumed you had some reason to use the `cookie_file`. If you don't I'd probably prefer to just remove everything that refers to it for simplicity.

**Comment by peppekerstens** [comment]
https://requests.readthedocs.io/en/latest/user/advanced/

requests.Session handles all for you.

@musantro why would you want to use a cookie_file?  I do not get the point/reason. can you elaborate?

i propose to get rid of any residual cookie code if there is no specific use-case for it

**Comment by musantro** [comment]
That's right @peppekerstens I was confused sorry for that. I thought we were not using cookies within the library, but `requests.Session` does.

Then I think the same, we should get rid of any residual cookie code. Maybe we should focus the issue on that

**Comment by jasondilworth56** [comment]
Yea, I'm on board with that for sure. If anyone fancies taking it on and putting in the PR I'm more than happy with that, but otherwise it's on the list for an update soon 👍
