### ISSUE TITLE
league_season_sessions is unable to get results from retired league seasons

### ISSUE THREAD

**Issue by peppekerstens** [jasondilworth56/iracingdataapi#15]
```python
league_id = 5606
league_seasons = idc.league_seasons(league_id, retired=True) 
```

gets the retired seasons fine. however:

```python
league_id = 5606
season_id = 83043
league_season_sessions = idc.league_season_sessions(league_id, season_id)
```

spawns the result from current active season (without error) instead of the retired season.

to check yourself; 
the retired season contains a host session_id 58362796 (and most session are with the 5xxxxxxx range)
current season session_id's are in the 18xxxxxxx / 19xxxxxxx range.

**Comment by jasondilworth56** [comment]
@peppekerstens I've just had a chance to use your example and I'm wondering if maybe you're mixing up `session_id` with `subsession_id`?

For instance, your example of `58362796` is in there under `subsession_id` but the `session_id` for that session is `193716023`.

**Comment by peppekerstens** [comment]
i'll double check...might be PEBCAK :|

**Comment by peppekerstens** [comment]
confirmed.  thanks

**Comment by jasondilworth56** [comment]
No worries, glad to get to the bottom of it!
