### ISSUE TITLE
Feature Request: add get_doc function

### ISSUE THREAD

**Issue by peppekerstens** [jasondilworth56/iracingdataapi#17]
```python
    def get_doc(self, service, method):
        docpath = "/data/doc/" + service + "/" + method
        return self._get_resource(docpath)
```

**Comment by musantro** [comment]
I think this would be more a resource for the `iracingdataapi` developer rather than the final user instead. 
What it could be better maybe is to add doscstrings to all the API methods to ease the final user implementation

**Comment by NoHeDidnt** [comment]
Generally, I think this could be usefull. But it doesn't need to have `service` & `method` arguments. The response data of the main `/data/doc` endpoint includes all docs, unless iRacing changed something recently.

**Comment by jasondilworth56** [comment]
I think I'm with @musantro on this one at the moment. It would be great to add docstrings everywhere, this is definitely one of the areas where it's clear that this was originally thrown together in an afternoon for something we needed behind the scenes at NOMAD.

**Comment by peppekerstens** [comment]
Use-case is/was indeed to ease/help with further dev/bugfixing of iracingdataapi, not anything else...

**Comment by peppekerstens** [comment]
> Generally, I think this could be usefull. But it doesn't need to have `service` & `method` arguments. The response data of the main `/data/doc` endpoint includes all docs, unless iRacing changed something recently.

see.... i didn't know.  would have made my life ,uch simpler :)

**Comment by musantro** [comment]
I still don't see why it should be a public method. But if I were to put this method, maybe I would set it as [private method using Python conventions](https://docs.python.org/3/tutorial/classes.html#tut-private).
