### ISSUE TITLE
Lap time format issue

### ISSUE THREAD

**Issue by Jamesburgess1312** [jasondilworth56/iracingdataapi#18]
The result_lap_data() methods lap time data is formatted in a way that it is not usable. Is there any way to fix this?

**Comment by jasondilworth56** [comment]
How do you mean not usable? It is the number provided directly by iRacing, multiply it by 10000 to get the number of seconds.

**Comment by Jamesburgess1312** [comment]
I did not try that thank you for the assistance. Much appreciated.

**Comment by jasondilworth56** [comment]
No worries @Jamesburgess1312, enjoy!
