### ISSUE TITLE
Create docstrings for all the public methods

### ISSUE THREAD

**Issue by musantro** [jasondilworth56/iracingdataapi#20]
Following the conversation on #17 , It would be great to have docstrings and document the Class and its methods.

For starters... 

- [x] which docstring syntax are we are going to stick with? (RestructuredText, Google, Numpy...) -> google

**Comment by NoHeDidnt** [comment]
RestructuredText is what I used so far, but I'm always open to try something new... _Numpy maybe?_

As you mentioned, we will have to stick to one, that part matters the most, imo.

**Comment by jasondilworth56** [comment]
I'm happy with whatever the consensus is – do you have a preference @musantro?

**Comment by musantro** [comment]
I have experience with ReStructuredText, although I find it quite verbose. Google/Numpy seem to be more attractive as it is more concise. I would like to try with Google / Numpy, whatever you guys like the most.

* Almost all IDEs support those docstring syntaxes
* All can be used to generate docs (using `sphinx`, for example) in case we would like to generate docs sometime in the future.

But it seems that Google seems slightly more condensed (please see [this](https://betterprogramming.pub/3-different-docstring-formats-for-python-d27be81e0d68)

So I'd go for Google for this time. What do you guys think?

**Comment by jasondilworth56** [comment]
I'm happy to go with Google – I haven't used it before but it seems like a good compromise.

**Comment by musantro** [comment]
Okay, so Google then. I will provide a tentative PR when it's ready.

**Comment by peppekerstens** [comment]
nice!
