### ISSUE TITLE
Error in _get_resource_or_link

### ISSUE THREAD

**Issue by 23Kev** [jasondilworth56/iracingdataapi#23]
I'm using iracingdataapi with the consistency_tracker (https://github.com/mrzepka/iRacingConsistencyTracker) and have got an issue as follows.
I checked with Matt, dev for consistency tracker and he mentioned the error is in iracingdataapi. I don't understand things enough to fix it.
Hope the below is useful. Let me know if you want me to test anything else.

```
working on subsession: 60496591
working on subsession: 60496592
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 1090, in <module>
    main(cust_id=_cust_id, subsession_id=_subsession_id, last_x=_last_x, series_id=_series_id, year=_year, season=_season)
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 1067, in main
    subsession_looper(subsession_id_list, cust_id)
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 975, in subsession_looper
    laps = get_laps(subses, customers, is_team_event, cust_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 845, in get_laps
    get_all_session_laps(subsession_id=subsession_id,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 303, in get_all_session_laps
    laps, clean_lap_count = get_lap_data_for_subsession_and_cust(subsession_id, customer, simsession_number)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Utils\iRacingData\iRacingConsistencyTracker - Series\consistency_tracker.py", line 255, in get_lap_data_for_subsession_and_cust
    lap_results = idc.result_lap_data(subsession_id=subsession_id, cust_id=cust_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\site-packages\iracingdataapi\client.py", line 280, in result_lap_data
    resource = self._get_resource("/data/results/lap_data", payload=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\site-packages\iracingdataapi\client.py", line 90, in _get_resource
    resource_obj, is_link = self._get_resource_or_link(request_url, payload=payload)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\site-packages\iracingdataapi\client.py", line 81, in _get_resource_or_link
    raise RuntimeError(r.json())
                       ^^^^^^^^
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jasondilworth56** [comment]
I'll take a look into that if you can fire over the subsession ID and customer ID that it failed on. I think I can see that it's subsession `60496592` but can't see the cust_id in what you've pasted.

**Comment by 23Kev** [comment]
I don't think its consistent. I tried querying that subsession ID again and it worked fine. I've also had the error with other scripts that I'm using and its, unfortunately, inconsistent. It does generally happen after a long running script, eg. this one was running for about 3 hours when it failed, and another failed after a similar amount of time. I'm also running these scripts on two different computers, although with the same version of Python on both. What version do you suggest?

**Comment by 23Kev** [comment]
Also, for the issue I posted above, I was only querying the subsession and am not using the customer ID.

**Comment by NoHeDidnt** [comment]
The problem seems to be this: `raise RuntimeError(r.json())`. Similar to #11, this happens when a driver didn't complete any laps in a session, for example, and an empty JSON is returned. The question is: Do we need the JSON data for raising the error? 

If we don't, then either `raise RuntimeError(r)` or `raise RuntimeError("ERROR_MESSAGE")` could be used instead. 

But, if we do need the JSON data, the call to `r.json()` should be placed inside a try-except block to catch the `JSONDecodeError` that is raised if the data is empty.

**Comment by 23Kev** [comment]
So its happened a few times with a different script. In this I am only using the iracingdataapi functions, specifically I'm looping through every member and getting their iRating. 

Pasted another error below. I have looked at the member_info for this customer ID and other than having no iRating properties, there is nothing different to other customers. I am handling if there is no irating property in my script, so it won't be that (I don't think). I've checked some other member ids that failed and there is nothing similar between them.

I really think its a timeout type issue, but unsure how I can tell if thats the case. I'm a bit of a python noob (I mainly got ChatGPT to create this script for me, bloody amazing) so unsure what I can do to fix it.

Error below.
member number:78632
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\
__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\
decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\
decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\TempiRacing\GetMemberData.py", line 33, in <module>
    member_info = idc.member(cust_id=member_number, include_licenses=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TempiRacing\client.py", line 767, in member
    return self._get_resource("/data/member/get", payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TempiRacing\client.py", line 83, in _get_resource
    resource_obj, is_link = self._get_resource_or_link(request_url, payload=payl
oad)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^
  File "G:\TempiRacing\client.py", line 74, in _get_resource_or_link
    raise RuntimeError(r.json())
                       ^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jasondilworth56** [comment]
> The problem seems to be this: raise RuntimeError(r.json()). Similar to https://github.com/jasondilworth56/iracingdataapi/issues/11, this happens when a driver didn't complete any laps in a session, for example, and an empty JSON is returned. The question is: Do we need the JSON data for raising the error?

Absolutely right, but I'm also interested in why we're getting there – at that point we're authorised and not rate limited, so there's another reason for the failure. So raising with `r` is probably the way to go.

**Comment by NoHeDidnt** [comment]
My best guess would have been that it's a similar situation to #11. But I'm not so sure about that anymore, since the response has a code other than 200 (or something else that gets handled). I'm interested to see what code this is, now that it should be included in the error message.

**Comment by 23Kev** [comment]
I've grabbed the update, so will test it out now. Will let you know how it goes.
Thanks!

**Comment by 23Kev** [comment]
The new error has shown itself.
`member number:397333
Traceback (most recent call last):
  File "G:\TempiRacing\GetMemberData.py", line 33, in <module>
    member_info = idc.member(cust_id=member_number, include_licenses=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TempiRacing\client.py", line 767, in member
    return self._get_resource("/data/member/get", payload=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\TempiRacing\client.py", line 83, in _get_resource
    resource_obj, is_link = self._get_resource_or_link(request_url, payload=payl
oad)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^
  File "G:\TempiRacing\client.py", line 74, in _get_resource_or_link
    raise RuntimeError("Unhandled Non-200 response", r)
RuntimeError: ('Unhandled Non-200 response', <Response [502]>)`

Let me know if its just a issue I need to deal with, I do have a way to continue doing what I need to do, so its not critical for me.

**Comment by jasondilworth56** [comment]
Once we get to 502 errors that's kind of out of our control – your connection with iRacing at that point is the weak point for whatever reason.

While we _could_ fail quietly on things like this, I think it's worth throwing the errors when they happen and have whatever is using `iracingdataapi` make their own choice on how to handle them.
