### ISSUE TITLE
Is it a missing feature?

### ISSUE THREAD

**Issue by mathgenius1991712** [jasondilworth56/iracingdataapi#25]
Before I suggest a problem, I would like to express my grateful attitude to you.
Thanks

I am using this library to build a simple python script which pulls data from iRacing site.
And I am retrieving the result of session using your result() method.
I gave the parameter subsession_id and include_licenses = True to get the Safety Rating of each driver after session
But I can't get that value or maybe I don't know what value it corresponds to

It would be grateful if you fix this

And also it would be good if you make a documentation which is more friendly for methods and variables

Thanks again

**Comment by jasondilworth56** [comment]
Thanks for the kind words. The license information of each driver is returned with the `include_licenses` option set to `True` as you've checked. You can find it within each result under `new_license_level` and `new_sub_level`, with the `old_` prefix used to see where they've come from.

For instance, you could get the license level of the last driver result from the last session of a result like this:
```python
result = ird.result(subsession_id=SUBSESSION, include_licenses=True)
last_session = result['session_results'][-1]
last_driver = last_session['results'][-1]
print(f"New license level: {last_driver['new_license_level']} New license sub level: {last_driver['new_sub_level']}")
```

The way to convert the license level and sub level into SR the way that it's shown around iRacing is somewhere in the iRacing official docs from the forums, although I'm away from my PC at the moment.

**Comment by jasondilworth56** [comment]
You can get the license levels with:
`ird._get_resource("/data/lookup/licenses")`
And the sub level is the SR * 100
