### ISSUE TITLE
  Update to non-functional sample code

### ISSUE THREAD

**Issue by CDNHammer012** [jasondilworth56/iracingdataapi#26]
Sorry if this submission is incorrect, I'm a novice Python user.

It seems that the sample code is incorrect/outdated.  The methods may have been updated since the sample code was created. Correction would be:

```
from iracingdataapi.client import irDataClient

idc = irDataClient(username=[YOUR iRACING USERNAME], password=[YOUR iRACING PASSWORD])

# get the summary data of a member
idc.stats_member_summary(cust_id=20979)


# get latest results of a member
idc.stats_member_recent_races(cust_id=20979)


# get all laps for a specific driver in a race
idc.result_lap_data(subsession_id=43720351, cust_id=20979)
```

Also it required me to install chardet (pip install chardet) as it was a new environment install. 
Thank you very much for the work you have done!!!

**Comment by jasondilworth56** [comment]
Thanks for bringing that up @CDNHammer012, I appreciate it.
