### ISSUE TITLE
Login sources?!

### ISSUE THREAD

**Issue by DevDanielGomez** [jasondilworth56/iracingdataapi#27]
Hey, Your wrapper looks and works great. Great Job!
I have a requirement to try to find login sources in an account.. pretty similiar to what iracing used to have on the UI.

I run a league and ultimately odd stuff has being happening, just wanna make sure everything is the way is supposed to be.

Have you seen something like in that api?

**Comment by jasondilworth56** [comment]
Hi @DevDanielGomez, no I haven't seen anything around login sources in the API. Are you hoping to see where people have used `iracingdataapi` or just all sources of logins for your account? 

If it's the latter I think your best shot would be changing your password, then getting in touch with iRacing support and asking them to invalidate any sessions on your account. That'll just help make sure there's noone logged in that shouldn't be.
