### ISSUE TITLE
driver_stats_by_category endpoints not in 1.2.1 update via pip

### ISSUE THREAD

**Issue by cwitt** [jasondilworth56/iracingdataapi#32]
Just updated to v. 1.2.1 using pip, and I'm not seeing the 'driver_stats_by_category' merged changes in my local version of client.py.

**Comment by jasondilworth56** [comment]
Hi @cwitt, sorry for the delay but yes there was an issue with how I uploaded it. I've skipped through to 1.2.2 which does now have the correct endpoint as well as a couple of other updates described in https://github.com/jasondilworth56/iracingdataapi/releases/tag/v1.2.2
