### ISSUE TITLE
Heat Races eventlogs

### ISSUE THREAD

**Issue by AndiSenior** [jasondilworth56/iracingdataapi#38]
The result_event_log() function provides the simsession_number as an argument. How can I read out the event logs in a heat race, which consists of a heat and a feature race, for example?

**Comment by jasondilworth56** [comment]
I don't have a `subsession` to hand, but the `simsession_number` is 0 for race and then decremented for every session before it – I assume that the heat races are down as  `simsession_number` -1, -2, etc working back towards practice.
