### ISSUE TITLE
Auth no longer working?

### ISSUE THREAD

**Issue by cwitt** [jasondilworth56/iracingdataapi#40]
It looks as if auth to the iRacing API in my Python code (using this library) is failing with a 'Legacy authorization refused' error since the end of September. I was happy it seemed to continue to work following the final shutdown of the legacy site, but apparently that was short-lived. I loved this library mostly because it made the obtuse authentication to the API easier to manage. Is anyone else seeing this issue? Is there a good work-around? Thanks.

**Comment by cwitt** [comment]
Found the other thread and the fix. Resolved.

**Comment by cwitt** [comment]
Found the link to the forum post. Fixed. Thanks.

**Comment by jasondilworth56** [comment]
Glad you found what you needed and also glad you're getting some good use out of the wrapper!
