### ISSUE TITLE
Legacy auth refused

### ISSUE THREAD

**Issue by skiddolo** [jasondilworth56/iracingdataapi#41]
hi, from about 10days or something i've always this error

`('Error from iRacing: ', {'authcode': 0, 'inactive': False, 'message': 'Legacy authorization refused.', 'verificationRequired': False})`

this is the request

`idc = irDataClient(username, password)`

maybe is changed smth?

**Comment by jasondilworth56** [comment]
Hi @skiddolo, sorry you're having issues. The good news is this can be sorted quickly, the bad news is there's nothing I can do specifically in this wrapper for you. See here for more info on a previously closed issue:

https://github.com/jasondilworth56/iracingdataapi/issues/39

**Comment by skiddolo** [comment]
thx 👍
